"""add provider to model_configs

Revision ID: 1db1ebc908e4
Revises: 2952aa9a98f3
Create Date: 2025-11-21 16:08:46.619774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db1ebc908e4'
down_revision: Union[str, Sequence[str], None] = '2952aa9a98f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('provider', sa.String(length=50), server_default='openai', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'provider')
    # ### end Alembic commands ###
