"""add_provider_to_model_configs

Revision ID: 8136c8a57cbb
Revises: 2952aa9a98f3
Create Date: 2025-10-26 21:24:30.986948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8136c8a57cbb'
down_revision: Union[str, Sequence[str], None] = '2952aa9a98f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework')
    op.add_column('model_configs', sa.Column('provider', sa.String(length=50), server_default='openai', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'provider')
    op.create_table('homework',
    sa.Column('taskrefid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('homework_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('schedule_task', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('detail_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detail_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('taskrefid', name=op.f('homework_pkey'))
    )
    # ### end Alembic commands ###
