"""add_output_mode_to_works

Revision ID: 906ca23fbfe1
Revises: 1db1ebc908e4
Create Date: 2025-11-30 00:26:33.895695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906ca23fbfe1'
down_revision: Union[str, Sequence[str], None] = '1db1ebc908e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('output_mode', sa.String(length=20), server_default='markdown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'output_mode')
    # ### end Alembic commands ###
